Refactor filterWordMatches to resolve error
Error: Uncaught (in promise) SyntaxError: Invalid regular expression... Maximum call stack size exceeded

Converting to an async function seems to have resolved the issue. Try...catch may no longer be necessary